-- Adicionar coluna de código sequencial na tabela organizations
-- Execute no SQL Editor do Supabase

-- Adiciona a coluna com autoincremento
ALTER TABLE organizations 
ADD COLUMN IF NOT EXISTS codigo BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Opcional: Se quiser que comece de um número específico (ex: 1)
-- ALTER SEQUENCE organizations_codigo_seq RESTART WITH 1;

-- Atualizar registros existentes (se necessário, mas o ADD COLUMN já deve preencher se tiver identity)
-- Como é GENERATED BY DEFAULT AS IDENTITY, ele deve preencher para novos. 
-- Para antigos, eles ficarão com NULL se não for feito o backfill, mas IDENTITY costuma cuidar disso.
-- Se ficarem NULL, rode:
-- UPDATE organizations SET codigo = (SELECT count(*) FROM organizations o2 WHERE o2.created_at <= organizations.created_at);
